typedef enum {
  RELAY_CONTROL_SYSTEM_IDLE,
  RELAY_CONTROL_SYSTEM_ON,
  RELAY_CONTROL_SYSTEM_OFF
} RELAY_CONTROL_STATE;

#define RELAY_1 3
#define RELAY_2 4
#define RELAY_3 5
#define RELAY_4 6
#define RELAY_CONTROL A3
#define RELAY_ANALOG_VOLT 6
